name: Soup
main: me.krouda.soup.Soup
version: ${project.version}
commands:
  setspawn:
    description: set spawn
    usage: /setspawn
    aliases: [spawnset, setlobby]
  spawn:
      description: teleport to spawn
      usage: /spawn
      aliases: [spawn, lobby]